stages:
- test
- deploy

variables:
  PYTHON_IMAGE: python:3.10-slim-buster

test-api:
  stage: test
  image: "$PYTHON_IMAGE"
  coverage: "/^TOTAL.+?(\\d+\\%)$/"
  before_script:
  - pip3 install -r requirements-dev.txt
  script:
  - pytest --cov=app tests/

test-migrations-sqlite:
  variables:
    DATABASE_URL: sqlite:///db.sqlite
  stage: test
  image: "$PYTHON_IMAGE"
  before_script:
  - pip3 install -r requirements-dev.txt
  script:
  - python3 app/run_migration.py

test-migrations-mysql:
  variables:
    MYSQL_PASSWORD: mysql
    MYSQL_USER: mysql
    MYSQL_DATABASE: mysql
    DATABASE_URL: mysql+pymysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql-test-db/$MYSQL_DATABASE?charset=utf8mb4
  services:
    - name: mysql:8
      alias: mysql-test-db
  stage: test
  image: "$PYTHON_IMAGE"
  before_script:
  - pip3 install -r requirements-dev.txt
  script:
  - python3 app/run_migration.py

pages:
  stage: deploy
  image: "$PYTHON_IMAGE"
  before_script:
  - pip3 install mkdocs-material
  script:
  - cd docs
  - mkdocs build --strict --verbose
  - cp -r site/ ../public/
  artifacts:
    paths:
    - public
  only:
    changes:
      - docs/**/*

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
