stages:
- test
- deploy
- build

variables:
  PYTHON_IMAGE: python:3.10-slim-buster

test-api-sqlite:
  cache:
    paths:
      - .cache/pip
      - venv/
  variables:
    DATABASE_URL: sqlite:///db.sqlite
  stage: test
  image: "$PYTHON_IMAGE"
  coverage: "/^TOTAL.+?(\\d+\\%)$/"
  before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  script:
  - pip3 install -r requirements-dev.txt
  - pytest --cov=app tests/

pages:
  cache:
    paths:
      - .cache/pip
      - venv/
  stage: deploy
  image: "$PYTHON_IMAGE"
  before_script:
  - pip3 install mkdocs-material
  script:
  - cd docs
  - mkdocs build --strict --verbose
  - cp -r site/ ../public/
  artifacts:
    paths:
    - public
  only:
    changes:
      - docs/**/*

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml


buid-image:
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/psenna/image-databases-api
  services:
    - docker-dind:latest
  image: docker:latest
  stage: build
  only:
  - tags
  script:
    - docker build -t $CONTAINER_IMAGE:$CI_COMMIT_TAG .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_TAG
    - docker tags $CONTAINER_IMAGE:$CI_COMMIT_TAG $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:lates