stages:
- test
- deploy

variables:
  PYTHON_IMAGE: python:3.10-slim-buster

test-api-sqlite:
  cache:
    paths:
      - .cache/pip
      - venv/
  stage: test
  image: "$PYTHON_IMAGE"
  coverage: "/^TOTAL.+?(\\d+\\%)$/"
  before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  script:
  - pip3 install -r requirements-dev.txt
  - pytest --cov=app tests/


test-api-mysql:
  cache:
    paths:
      - .cache/pip
      - venv/
  variables:
    MYSQL_PASSWORD: mysql
    MYSQL_USER: mysql
    MYSQL_DATABASE: mysql
    DATABASE_URL: mysql+pymysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql-test-db/$MYSQL_DATABASE?charset=utf8mb4
  services:
    - name: mysql:8
      alias: mysql-test-db
  stage: test
  image: "$PYTHON_IMAGE"
  coverage: "/^TOTAL.+?(\\d+\\%)$/"
  before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  script:
  - pip3 install -r requirements-dev.txt
  - pytest --cov=app tests/

test-api-postgres:
  cache:
    paths:
      - .cache/pip
      - venv/
  variables:
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
    POSTGRES_DB: postgres
    POSTGRES_HOST: postgres-test-db
    DATABASE_URL: postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB
  services:
    - name: postgres:14
      alias: postgres-test-db
  stage: test
  image: "$PYTHON_IMAGE"
  coverage: "/^TOTAL.+?(\\d+\\%)$/"
  before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  script:
  - pip3 install -r requirements-dev.txt
  - pytest --cov=app tests/

pages:
  cache:
    paths:
      - .cache/pip
      - venv/
  stage: deploy
  image: "$PYTHON_IMAGE"
  before_script:
  - pip3 install mkdocs-material
  script:
  - cd docs
  - mkdocs build --strict --verbose
  - cp -r site/ ../public/
  artifacts:
    paths:
    - public
  only:
    changes:
      - docs/**/*

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
